Revise timeout limitation

diff --git a/templates/aml-cli-v2/run-pipeline.yml b/templates/aml-cli-v2/run-pipeline.yml
--- a/templates/aml-cli-v2/run-pipeline.yml
+++ b/templates/aml-cli-v2/run-pipeline.yml
@@ -12,44 +12,45 @@ parameters:
     type: string
     default: 'false'
 
-- job: Test
-  timeoutInMinutes: 0 # how long to run the job before automatically cancelling, 0 represent utilize maximum capacity(6hr)
-  cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
-  steps:
-    - task: AzureCLI@2
-      displayName: Run Azure ML pipeline
-      continueOnError: true
-      inputs: 
-        azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level 
-        scriptType: bash
-        workingDirectory: $(System.DefaultWorkingDirectory)
-        scriptLocation: inlineScript
-        inlineScript: |
-          run_id=$(az ml job create -f ${{ parameters.pipeline_file }} \
-            --set experiment_name=${{ parameters.experiment_name }} \
-            --set inputs.enable_monitoring=${{ parameters.enable_monitoring }} \
-            display_name=${{ parameters.display_name }} --query name -o tsv)
-          if [[ -z "$run_id" ]]
-          then
-            echo "Job creation failed"
-            exit 3
-          fi
-          az ml job show -n $run_id --web
-          status=$(az ml job show -n $run_id --query status -o tsv)
-          if [[ -z "$status" ]]
-          then
-            echo "Status query failed"
-            exit 4
-          fi
-          running=("NotStarted" "Queued" "Starting" "Preparing" "Running" "Finalizing" "CancelRequested")
-          while [[ ${running[*]} =~ $status ]]
-          do
-            sleep 15 
+jobs:
+  - job: Test
+    timeoutInMinutes: 0 # how long to run the job before automatically cancelling, 0 represent utilize maximum capacity(6hr)
+    cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
+    steps:
+      - task: AzureCLI@2
+        displayName: Run Azure ML pipeline
+        continueOnError: true
+        inputs: 
+          azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level 
+          scriptType: bash
+          workingDirectory: $(System.DefaultWorkingDirectory)
+          scriptLocation: inlineScript
+          inlineScript: |
+            run_id=$(az ml job create -f ${{ parameters.pipeline_file }} \
+              --set experiment_name=${{ parameters.experiment_name }} \
+              --set inputs.enable_monitoring=${{ parameters.enable_monitoring }} \
+              display_name=${{ parameters.display_name }} --query name -o tsv)
+            if [[ -z "$run_id" ]]
+            then
+              echo "Job creation failed"
+              exit 3
+            fi
+            az ml job show -n $run_id --web
             status=$(az ml job show -n $run_id --query status -o tsv)
-            echo $status
-          done
-          if [[ "$status" != "Completed" ]]  
-          then
-            echo "Training Job failed or canceled"
-            exit 3
-          fi
+            if [[ -z "$status" ]]
+            then
+              echo "Status query failed"
+              exit 4
+            fi
+            running=("NotStarted" "Queued" "Starting" "Preparing" "Running" "Finalizing" "CancelRequested")
+            while [[ ${running[*]} =~ $status ]]
+            do
+              sleep 15 
+              status=$(az ml job show -n $run_id --query status -o tsv)
+              echo $status
+            done
+            if [[ "$status" != "Completed" ]]  
+            then
+              echo "Training Job failed or canceled"
+              exit 3
+            fi
